$script_mysql = <<-SCRIPT
  apt-get update && \
  apt-get install -y mysql-server-5.7 && \
  mysql -e "create user 'phpuser'@'%' identified by 'pass';"
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"

  # config.vm.define "mysqldb" do |mysql|
  #   mysql.vm.network "public_network", ip: "192.168.1.24", bridge: "Intel(R) Wi-Fi 6 AX200 160MHz"

  #   mysql.vm.provision "shell",
  #     inline: "cat /configs/id_bionic.pub >> .ssh/authorized_keys"
  #   mysql.vm.provision "shell", inline: $script_mysql
  #   mysql.vm.provision "shell",
  #     inline: "cat /configs/mysqld.cnf > /etc/mysql/mysql.conf.d/mysqld.cnf"
  #   mysql.vm.provision "shell", inline: "service mysql restart"

  #   mysql.vm.synced_folder "./configs", "/configs"
  #   mysql.vm.synced_folder ".", "/vagrant", disabled: true
  # end

  config.vm.define "phpweb" do |phpweb|
    phpweb.vm.provider "virtualbox" do |vm|
      vm.memory = 512
      vm.cpus = 1
      vm.name = "ubuntu_bionic_phpweb"
    end
    phpweb.vm.network "forwarded_port", guest: 8888, host: 8889
    phpweb.vm.network "public_network", ip: "192.168.1.25", bridge: "Intel(R) Wi-Fi 6 AX200 160MHz"

    phpweb.vm.provision "shell",
      inline: "apt-get update && apt-get install -y puppet"

    phpweb.vm.provision "puppet" do |puppet|
      puppet.manifests_path = "./configs/manifests"
      puppet.manifest_file = "phpweb.pp"
    end
  end

  config.vm.define "mysqlserver" do |mysqlserver|
    mysqlserver.vm.provider "virtualbox" do |vm|
      vm.memory = 512
      vm.cpus = 1
      vm.name = "ubuntu_bionic_mysqlserver"
    end
    mysqlserver.vm.network "public_network", ip: "192.168.1.22", bridge: "Intel(R) Wi-Fi 6 AX200 160MHz"
    mysqlserver.vm.provision "shell",
      inline: "cat /vagrant/configs/id_bionic.pub >> .ssh/authorized_keys"
  end

  config.vm.define "ansible" do |ansible|
    # ansible.vm.network "public_network", ip: "192.168.1.26", bridge: "Intel(R) Wi-Fi 6 AX200 160MHz"
    ansible.vm.provider "virtualbox" do |vm|
      vm.memory = 512
      vm.cpus = 1
      vm.name = "ubuntu_bionic_ansible"
    end

    ansible.vm.provision "shell",
      inline: "apt-get update &&  \
               apt-get install -y software-properties-common && \
               apt-add-repository --yes --update ppa:ansible/ansible && \
               apt-get install -y ansible "

    ansible.vm.provision "shell",
        inline: "cp /vagrant/id_bionic /home/vagrant/id_bionic && \
                chmod 600 /home/vagrant/id_bionic"

    ansible.vm.provision "shell",
        inline: "ansible-playbook -i /vagrant/configs/ansible/hosts \
                  /vagrant/configs/ansible/playbook.yml"
  end

  config.vm.define "memcached" do |memcached|
    memcached.vm.box = "centos/7"
    memcached.vm.provider "virtualbox" do |vb|
      vb.memory = 512
      vb.cpus = 1
      vb.name = "centos7_memcached"
    end
  end

  config.vm.define "dockerhost" do |dockerhost|
    dockerhost.vm.provider "virtualbox" do |vb|
      vb.memory = 512
      vb.cpus = 1
      vb.name = "ubuntu_dockerhost"
    end
    dockerhost.vm.provision "shell",
    inline: "apt-get update &&  \
    apt-get install -y docker.io"
  end

end